services:
  - type: web
    name: decision-assistant-backend
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DEEPSEEK_API_KEY
        sync: false  # 需要在 Render Dashboard 中手动设置
    healthCheckPath: /health
    plan: free
